package life.majiang.community.model;

public class Liked {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKED.ID
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKED.LIKE_CREATOR
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    private Long likeCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKED.GMT_CREATE
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKED.GMT_MODIFIED
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKED.LIKE_COMMENT
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    private Long likeComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKED.STATUS
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKED.ID
     *
     * @return the value of LIKED.ID
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKED.ID
     *
     * @param id the value for LIKED.ID
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKED.LIKE_CREATOR
     *
     * @return the value of LIKED.LIKE_CREATOR
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    public Long getLikeCreator() {
        return likeCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKED.LIKE_CREATOR
     *
     * @param likeCreator the value for LIKED.LIKE_CREATOR
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    public void setLikeCreator(Long likeCreator) {
        this.likeCreator = likeCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKED.GMT_CREATE
     *
     * @return the value of LIKED.GMT_CREATE
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKED.GMT_CREATE
     *
     * @param gmtCreate the value for LIKED.GMT_CREATE
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKED.GMT_MODIFIED
     *
     * @return the value of LIKED.GMT_MODIFIED
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKED.GMT_MODIFIED
     *
     * @param gmtModified the value for LIKED.GMT_MODIFIED
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKED.LIKE_COMMENT
     *
     * @return the value of LIKED.LIKE_COMMENT
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    public Long getLikeComment() {
        return likeComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKED.LIKE_COMMENT
     *
     * @param likeComment the value for LIKED.LIKE_COMMENT
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    public void setLikeComment(Long likeComment) {
        this.likeComment = likeComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKED.STATUS
     *
     * @return the value of LIKED.STATUS
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKED.STATUS
     *
     * @param status the value for LIKED.STATUS
     *
     * @mbg.generated Fri Oct 25 14:27:02 CST 2019
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}